import { supabaseAdmin } from '@/lib/supabase-admin';
import { notFound } from 'next/navigation';

export default async function PDFRenderPage({ searchParams }: { searchParams: Promise<{ outfit_id?: string, secret?: string }> }) {
  const params = await searchParams;
  const { outfit_id, secret } = params;

  if (!outfit_id || secret !== process.env.WORKER_SECRET) {
    return notFound();
  }

  const { data: outfit } = await supabaseAdmin.from('user_outfits').select('*').eq('id', outfit_id).single();

  if (!outfit) return notFound();

  // In a real app we'd fetch actual inventory items using the slots mapping
  // Here we just render a simple mock up using IDs
  const slots = outfit.slots || {};


  return (
    <div className="bg-white min-h-screen text-black p-12 font-mono">
      <div className="border-4 border-black p-8">
        <h1 className="text-4xl font-black uppercase mb-2">DNA Brief</h1>
        <p className="text-sm uppercase tracking-widest text-zinc-500 mb-8">Generated by Auvra Society Mesh</p>

        <div className="grid grid-cols-2 gap-8">
          <div>
            <h2 className="text-xl font-black mb-4 border-b-2 border-black pb-2">Manifest: {outfit.name || 'Untitled Look'}</h2>
            <p className="text-xs uppercase">Outfit ID: {outfit.id}</p>
            <p className="text-xs uppercase">Date: {new Date(outfit.created_at).toLocaleDateString()}</p>
          </div>

          <div className="space-y-4">
            {Object.keys(slots).map(slot => (
              slots[slot] ? (
                <div key={slot} className="border border-black p-4">
                  <h3 className="text-xs font-black uppercase">{slot}</h3>
                  <p className="text-sm truncate">ID: {slots[slot]}</p>
                </div>
              ) : null
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
